import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './Providers'
import Navigation from './components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html className=" bg-slate-900" lang="en">
      <body>        
      <Providers>
          <Navigation/>
           {children}
        </Providers>
        </body>
    </html>
  )
}
